{% set name = "sardana-icepap" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ALBA-Synchrotron/sardana-icepap/archive/refs/tags/{{ version }}.tar.gz
  sha256: 34958bc36003a1db767bc17b1777fdf374b5bde726cff49b59439ac3254e9d5a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sardana
    - icepap

test:
  imports:
    - sardana_icepap
    - sardana_icepap.ctrl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ALBA-Synchrotron/sardana-icepap
  summary: IcePAP plugins for Sardana
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
    - rhomspuron
